#define SECRET_MQTT_HOST "[YOUR HA'S IP-ADDRES]"
#define SECRET_MQTT_PASS "[YOUR MQTT PASSWORD]"
#define SECRET_MQTT_PORT [YOUR MQTT PORT  example: 1883]
#define SECRET_MQTT_USER "[YOUR MQTT USERNAME]"
#define SECRET_PASS "[YOUR WIFI PASSWORD]"
#define SECRET_SSID "[YOUR WIFI NAME]"